export {
  DEFAULT_COLOR_CONSTRAINTS,
  DEFAULT_CONFIG,
  MAX_BOARD_SIZE,
  MIN_BOARD_SIZE,
  buildTilesFromColors,
  createNewGame,
  createNewGameForDifficulty,
  findBestAidMove,
  generateTrajectoryBoard,
  getCornerIndexes,
  getDifficultyTier,
  getLockedIndexes,
  getValidCrossDensities,
  getValidHorizontalLineCounts,
  getValidLineDensities,
  getValidVerticalLineCounts,
  isSolved,
  normalizeConfig,
  pickConfigForDifficulty,
  scrambleMovableTiles,
  swapTiles,
  type AidMove,
  type AppearanceConfig,
  type CornerColor,
  type CrossLockConfig,
  type DifficultyCatalogEntry,
  type DifficultyRating,
  type DifficultyTier,
  type GameConfig,
  type GameState,
  type GeneratedBoard,
  type LineLockConfig,
  type PuzzleSetupMode,
  type StructuralDifficultyMetrics,
  type Tile,
  type TrajectoryColorConfig
} from "../../../game";
export {
  analyzeBoardTiles,
  cssRgbToOklab,
  getOklabDistance,
  oklabToCss,
  oklabToRgb,
  parseCssRgb,
  rgbToCss,
  rgbToOklab,
  summarizeResearchSamples,
  type AxisMonotonicity,
  type BoardColorMetrics,
  type BoardResearchSample,
  type BoardResearchSummary,
  type BoardResearchSweep,
  type CenterChromaMetrics,
  type DistanceStats,
  type EdgeRampSmoothness,
  type MetricRange,
  type OklabColor,
  type ReadabilityHeuristic,
  type Rgb
} from "../../../colorAnalysis";
